#!/usr/bin/env python3
"""Derive packages/_defaults.yml from PCWM + the owned arch policy (CW-ADR-0012).

Inputs
  defaults/scraped_torch_matrix.json               what PyTorch actually publishes (PCWM),
                                        regenerated by fetch_torch_matrix.py
  defaults/python_cuda_torch_os_policy.yml  owned axis policy + generated rows

Outputs (in place)
  (same file)                           combinations: block regenerated in place
  defaults/phantom_combos.json          cells our grid implies but PCWM lacks
                                        (read by generate_matrix.py)

The derivation, per (cuda, torch-minor) present in PCWM:
  - skip CUDA lines not in supported_cudas (loud warning -- wiring the
    toolkit installer is a prerequisite, see .github/actions/setup-cuda)
  - pythons = PCWM's set for the pair, floored at python_min (no ceiling:
    torch's own python coverage IS the ceiling)
  - pytorch = newest patch PCWM ships for the pair
  - phantom cells = (cuda, torch, python, platform) our platform axis implies
    but PCWM does not ship (e.g. cu129 torch 2.10+ has no Windows)

Exit codes: 0 unchanged, 0 changed (prints diff summary), 2 on any error.
Never run at wheel-build time -- this is a maintenance step; build output
stays a function of the git SHA (CW-ADR-0012).

--dry-run: run the FULL derivation (parse, derive, splice, re-parse) but
write nothing. torch-matrix.yml runs this after every snapshot refresh so
that splice-anchor rot or upstream schema drift is discovered the day
upstream moves -- not months later at a maintainer's keyboard -- and opens
a GitHub issue on failure.
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
MATRIX = ROOT / "defaults" / "scraped_torch_matrix.json"
PCTO = ROOT / "defaults" / "python_cuda_torch_os_policy.yml"
PHANTOMS = ROOT / "defaults" / "phantom_combos.json"


def vkey(v):
    return [int(x) for x in v.split(".")]


def main() -> None:
    dry_run = "--dry-run" in sys.argv
    policy = yaml.safe_load(PCTO.read_text())
    pcwm = json.loads(MATRIX.read_text())["combos"]
    pmin = vkey(str(policy["python_min"]))
    supported = [str(c) for c in policy["supported_cudas"]]
    platforms = policy["platforms"]

    # Collect PCWM cells keyed by the EXACT torch patch release. Each row
    # pins one patch, so python sets and phantoms must come from that
    # patch's own cells -- unioning across patches hides holes (cu129
    # shipped Windows for 2.9.0 but NOT 2.9.1; a union sees "windows" and
    # emits no phantom, and every 2.9.1+cu129 Windows job dies at torch
    # install).
    pairs: dict[tuple, dict] = {}
    for c in pcwm:
        cuda_dotted = f"{c['cuda'][2:-1]}.{c['cuda'][-1]}"
        minor = ".".join(c["torch"].split(".")[:2])
        if "aarch64" in c["platform"]:
            plat = "linux_aarch64"
        elif "win" in c["platform"]:
            plat = "windows"
        else:
            plat = "linux"
        pairs.setdefault((cuda_dotted, minor), {}).setdefault(
            c["torch"], set()).add((c["python"], plat))

    skipped_cudas = sorted({cu for cu, _ in pairs} - set(supported), key=vkey)
    for cu in skipped_cudas:
        n = sum(1 for (c, _m) in pairs if c == cu)
        print(f"WARNING: PCWM ships cu{cu.replace('.', '')} ({n} torch minors) but "
              f"it is not in supported_cudas -- wire the toolkit installer in "
              f".github/actions/setup-cuda, then add it to the policy file",
              file=sys.stderr)

    rows, phantoms = [], []
    for (cuda, minor) in sorted(pairs, key=lambda k: (vkey(k[0]), vkey(k[1]))):
        if cuda not in supported:
            continue
        by_patch = pairs[(cuda, minor)]
        # Pin the newest patch that shipped x86 wheels; an aarch64-only
        # patch can't anchor a row (nothing to install on linux/windows).
        x86_patches = [t for t, cells in by_patch.items()
                       if any(pl != "linux_aarch64" for _, pl in cells)]
        if not x86_patches:
            continue
        chosen = max(x86_patches, key=vkey)
        cells = by_patch[chosen]
        pys = sorted({py for py, plat in cells if plat != "linux_aarch64"
                      and pmin <= vkey(py)}, key=vkey)
        if not pys:
            continue
        # Per-platform patch anchoring: when the chosen patch shipped ZERO
        # wheels for a platform but a sibling patch of the same minor did,
        # anchor that platform to the sibling instead of declaring the
        # whole line phantom there. Upstream really does this: cu129
        # Windows exists for 2.9.0 and not 2.9.1 -- the wheel tag promises
        # the minor (torch2.9), so the farm owes the line wherever ANY
        # patch shipped it. Partial per-python differences within a
        # platform stay with the chosen patch (normal upstream raggedness).
        overrides = {}
        plat_cells = {"linux": cells, "windows": cells, "linux_aarch64": cells}
        for pk in ("windows", "linux_aarch64"):
            if any(pl == pk for _, pl in cells):
                continue
            alts = [t for t, cs in by_patch.items()
                    if any(pl == pk for _, pl in cs)]
            if alts:
                alt = max(alts, key=vkey)
                overrides[pk] = alt
                plat_cells[pk] = by_patch[alt]
        row = {
            "cuda": cuda,
            "pytorch": chosen,
            "python_versions": pys,
        }
        for pk, alt in sorted(overrides.items()):
            row[f"pytorch_{pk}"] = alt
        rows.append(row)
        for py in pys:
            for plat in dict.fromkeys(platforms + ["linux_aarch64"]):
                key = plat if plat in ("windows", "linux_aarch64") else "linux"
                if (py, key) not in plat_cells[key]:
                    phantoms.append([cuda.replace(".", ""), minor,
                                     py.replace(".", ""), plat])

    # Splice the combinations block (the file's final section); keep the
    # owned policy sections above it untouched.
    text = PCTO.read_text()
    m = re.search(r"^combinations:\n(.*)\Z", text, re.M | re.S)
    if not m:
        raise SystemExit("ERROR: could not locate combinations block in "
                         "defaults/python_cuda_torch_os_policy.yml")
    block = ["combinations:",
             "  # GENERATED by scripts/derive_defaults.py from",
             "  # defaults/scraped_torch_matrix.json (PCWM). Do not hand-edit rows;",
             "  # edit the policy sections above and re-run."]
    cur = None
    for r in rows:
        if r["cuda"] != cur:
            cur = r["cuda"]
            block.append(f"  # ── cu{cur.replace('.', '')} ──")
        pyl = ", ".join(f'"{p}"' for p in r["python_versions"])
        block.append(f'  - cuda: "{r["cuda"]}"')
        block.append(f'    pytorch: "{r["pytorch"]}"')
        block.append(f"    python_versions: [{pyl}]")
        for k in sorted(r):
            if k.startswith("pytorch_"):
                block.append(f'    {k}: "{r[k]}"')
    new_text = text[:m.start()] + "\n".join(block) + "\n"

    old_rows = yaml.safe_load(text)["combinations"]
    new_rows = yaml.safe_load(new_text)["combinations"]
    if not new_rows:
        raise SystemExit("ERROR: derivation produced zero rows -- refusing")
    changed = new_rows != old_rows
    if not dry_run:
        PCTO.write_text(new_text)
        PHANTOMS.write_text(json.dumps(
            {"_comment": "Cells the grid implies but PCWM does not ship (CW-ADR-0007). "
                         "Generated by derive_defaults.py; read by generate_matrix.py.",
             "combos": sorted(phantoms)}, indent=1) + "\n")

    print(f"{'[dry-run] ' if dry_run else ''}{len(rows)} rows "
          f"({len(old_rows)} before, {'CHANGED' if changed else 'unchanged'}), "
          f"{len(phantoms)} phantom cells, "
          f"{len(skipped_cudas)} unsupported CUDA line(s) skipped: {skipped_cudas}")


if __name__ == "__main__":
    main()
