#!/usr/bin/env python3
"""Regenerate the package table in README.md from packages/ configs.

The table lives between the PACKAGE-TABLE markers and is derived from
the same loader everything else uses, so it cannot silently disagree
with the folders. Run after adding or changing a package:

    python scripts/update_readme_table.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from package_loader import iter_packages  # noqa: E402

BEGIN = "<!-- PACKAGE-TABLE:BEGIN (generated by scripts/update_readme_table.py) -->"
END = "<!-- PACKAGE-TABLE:END -->"

PLAT_SHORT = {"linux": "linux", "windows": "win", "linux_aarch64": "arm"}
ALL = ["linux", "windows", "linux_aarch64"]


def main():
    rows = []
    for folder, cfg in iter_packages():
        name = cfg["name"]
        repo = cfg["source_repo"]
        plats = (cfg.get("build_matrix") or {}).get("platforms") or ALL
        plat_s = " ".join(PLAT_SHORT[p] for p in ALL if p in plats)
        torch_axis = "torch-free" if cfg.get("links_torch") is False else "per-torch"
        rows.append(
            f"| [{name}](packages/{folder}/) "
            f"| [{repo}](https://github.com/{repo}) "
            f"| {torch_axis} | {plat_s} |")

    table = "\n".join([
        BEGIN,
        f"{len(rows)} packages.",
        "",
        "| Package | Source | Torch axis | Platforms |",
        "|---|---|---|---|",
        *rows,
        END,
    ])

    readme = ROOT / "README.md"
    text = readme.read_text()
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        text = head + table + tail
    else:
        anchor = "One folder per package under [`packages/`](packages/). "
        if anchor not in text:
            raise SystemExit("README anchor not found; place the markers by hand")
        text = text.replace(anchor, anchor + "\n\n" + table + "\n", 1)
    readme.write_text(text)
    print(f"README table: {len(rows)} packages")


if __name__ == "__main__":
    main()
